apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: Anurag-30
    provider: https://github.com
    providerKind: github
    repositories:
    - name: jenkinsx-cicd-node
    scheduler: in-repo
